runtime: python
env: flex
entrypoint: uwsgi --http :$PORT --static-map /static=static --static-map /media=media --static-map /favicon.ico=static/favicon.ico --wsgi-file cookbook/wsgi.py

beta_settings:
    cloud_sql_instances: ryorisho-app:us-central1:ryorisho-mysql

runtime_config:
  python_version: 3.5

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^venv/.*$

# google app engine management code
- ^google-cloud-sdk/.*$
- ^cloud-sql-proxy$

# Remove files/folders
- ^libs/.*$
- ^gulpfile.js$
- ^package.json$

# Centralize notes
- ^ideas$
- ^in-season$
- ^todo$
