# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT cookbook.wsgi

beta_settings:
    cloud_sql_instances: ryorisho:us-central1:ryorisho-mysql

runtime_config:
  python_version: 3
# [END runtime]
