runtime: python
env: flex
entrypoint: uwsgi --http :$PORT --static-map /static=static --static-map /media=media --static-map /favicon.ico=static/favicon.ico --wsgi-file cookbook/wsgi.py

beta_settings:
    cloud_sql_instances: ryorisho:us-central1:ryorisho-mysql

runtime_config:
  python_version: 3.5

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^venv/.*$

- ^google-cloud-sdk/.*$
- ^cloud-sql-proxy$
- ^Makefile$
- ^README.md$

- ^server-data-backup.json$

- ^libs/.*$
- ^gulpfile.js$
- ^package.json$

- ^ideas$
- ^in-season$
- ^todo$
