# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170228_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='equipment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeEquipment'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeIngredient'),
        ),
    ]
