#!/usr/bin/env python

import os
import sys
import django.core.wsgi
from distutils.sysconfig import get_python_lib

os.environ['DJANGO_SETTINGS_MODULE'] = 'cookbook.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'cookbook'))
os.environ['PYTHON_EGG_CACHE'] = get_python_lib()
application = django.core.wsgi.get_wsgi_application()
